MiBank_A3/Controllers/BillsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MiBank_A3.Attributes;
using MiBank_A3.Data;
using MiBank_A3.Models;
using MiBank_A3.ViewModels;
using MiBank_A3.Views;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.EntityFrameworkCore;

namespace MiBank_A3.Controllers
{
    [AuthorizeCustomer]
    public class BillsController : Controller
    {
        private readonly MiBankContextWrapper _context;
        private int CustomerId => HttpContext.Session.GetInt32(nameof(Customer.CustomerId)).Value;

        public BillsController(MiBankContext context)
        {
            _context = new MiBankContextWrapper(context);
        }


        const int BILL_PAGINATION_SIZE = 4;


        public IActionResult Index(int? id)
        {
            var vm = new BillListViewModel();
            vm.Bills = _context.GetBills(CustomerId);
            if(vm.Bills.Count == 0)
            {
                return View(vm);
            }
            var paginated = new Paginator<BillPay>(vm.Bills, id ?? 1);
            //go to first page if there was an error
            if(paginated.partialList == null)
            {
                return RedirectToAction(nameof(Index), new { id = 1 });
            }
            vm.Bills = paginated.partialList;
            vm.currentPage = paginated.currentPage;
            vm.nextPage = paginated.nextPage;
            vm.prevPage = paginated.prevPage;
            return View(vm);
        }

        public async Task<IActionResult> Pay(int? id)
        {
            BillPayViewModel vm;
            vm = new BillPayViewModel();
            if (id != null)
            {
                vm.Bill = await _context.GetBill(CustomerId,id);
            }
            else
            {
                vm.Bill = new BillPay();
            }
            vm.Payees = _context.GetAllPayees();
            vm.Customer = await _context.GetCustomerWithAccounts(CustomerId);

            return View(vm);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Pay(BillPayViewModel vm)
        {
            bool update = vm.Bill.BillPayId == 0 ? false : true;
            vm.Bill.Account = await _context.GetAccount(CustomerId, vm.Bill.AccountId);
            vm.Bill.Payee = await _context.GetPayee(vm.Bill.PayeeId);

            switch (vm.Bill.SchedulePayment())
            {
                case BillPayResult.FAIL_DATE:
                    ModelState.AddModelError($"Bill.{nameof(BillPay.ScheduleDate)}", "Date cannot be in the past");
                    goto ErrorCleanup;
                case BillPayResult.FAIL_NEGATIVE:
                    ModelState.AddModelError($"Bill.{nameof(BillPay.Amount)}", "Amount must be above 0");
                    goto ErrorCleanup;
                case BillPayResult.FAIL_FORMAT:
                    goto ErrorCleanup;
                case BillPayResult.OK:
                    if(update)
                    {
                        var oldBill = await _context.GetBill(vm.Bill.BillPayId, CustomerId);
                        //check we don't edit someone else's bill
                        if (oldBill == null)
                        {
                            ModelState.AddModelError($"Bill.{nameof(BillPay.BillPayId)}", "Illegal BillId in request");
                            goto ErrorCleanup;
                        }
                        //prevent 'Blocked' attribute from being set by users
                        vm.Bill.Blocked = oldBill.Blocked;
                        _context.UpdateBill(CustomerId, vm.Bill);
                    }
                    else
                    {
                        vm.Bill.Blocked = false;
                        _context.CreateBill(CustomerId, vm.Bill);
                    }
                    _context.SaveChangesAsync();
                    break;
            }
            if (update)
            {
                TempData["successMessage"] = $"Updated bill #{vm.Bill.BillPayId}.";
            }
            else
            {
                TempData["successMessage"] = $"Created bill #{vm.Bill.BillPayId}.";
            }
            
            return RedirectToAction(nameof(Index));
        ErrorCleanup:
            vm.Payees = _context.GetAllPayees();
            vm.Customer = await _context.GetCustomerWithAccounts(CustomerId);
            return View(vm);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var bill = await _context.GetBill(CustomerId,id);
            return View(bill);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(BillPay bill)
        {
            _context.DeleteBill(CustomerId, bill.BillPayId);
            TempData["successMessage"] = $"Deleted bill #{bill.BillPayId}.";
            return RedirectToAction("Index");
        }
    }
}

MiBank_A3/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MiBank_A3.Data;
using MiBank_A3.Models;
using MiBank_A3.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MiBank_A3.Controllers
{
    public class LoginController : Controller
    {
        private readonly MiBankContextWrapper _context;
        public LoginController(MiBankContext context)
        {
            _context = new MiBankContextWrapper(context);
        }

        // GET: LoginController
        public ActionResult Index()
        {
            ViewData["loginPage"] = true;
            return View();
        }

        // POST: LoginController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(LoginViewModel vm)
        {
            var customerId = await _context.Login(vm.Username, vm.Password);
            switch (customerId)
            {
                case (int)loginResult.MAX_ATTEMPTS:
                    ModelState.AddModelError(nameof(vm.Password), "Maximum login attempts exceeded");
                    return View(vm);
                case (int)loginResult.NO_PASSWORD:
                    ModelState.AddModelError(nameof(vm.Password), "No password entered");
                    return View(vm);
                case (int)loginResult.NO_USER:
                    ModelState.AddModelError(nameof(vm.Username), "User not found");
                    return View(vm);
                case (int)loginResult.WRONG_PASSWORD:
                    ModelState.AddModelError(nameof(vm.Password), "Username/password combination incorrect");
                    return View(vm);
            }

            HttpContext.Session.SetInt32(nameof(Customer.CustomerId), customerId);
            TempData["successMessage"] = "Logged in successfully.";
            return RedirectToAction("", "");
        }

        public ActionResult Logout()
        {
            TempData["successMessage"] = "Logged out successfully.";
            HttpContext.Session.Clear();
            return RedirectToAction("Index");
        }
    }
}

MiBank_A3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MiBank</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MiBank</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="" asp-action="Accounts">Accounts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="" asp-action="ATM">ATM</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bills" asp-action="Index">BillPay</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="" asp-action="Profile">Profile</a>
                        </li>
                        @if (ViewData["loginPage"] == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @if (TempData["successMessage"] != null){
                <div>
                    <span class="alert-info">@TempData["successMessage"]</span>
                </div>
            }
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MiBank - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>